### ISSUE TITLE
In landscape mode there is not way to change the views

### ISSUE THREAD

**Issue by KristelViidik** [unplugged/unplugged-controls#366] opened 2014-02-17 04:37 UTC
Environment:
Sony Xperia Z tablet Android 4.3

Steps to reproduce:
1. Open app in landscape mode

Expected result:
2. Views button displayed or clicking on the unplugged logo acts as views menu

Actual result:
2. Observe that instead of Views button there is the unplugged logo. Clicking on the logo does nothing.
![screenshot_2014-02-16-21-26-03](https://f.cloud.github.com/assets/2638956/2182504/2771e978-978d-11e3-89dc-90db06f9ed8f.png)

**Comment by whitemx** [comment] 2014-02-17 08:34
This is a duplicate of #363

**Closed as completed by whitemx** 2014-02-17 08:34 UTC
Labels: duplicate
